name: arxml-viewer-pro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.24.0
  - pandas>=2.1.0
  - matplotlib>=3.7.2
  - networkx>=3.1
  - pillow>=10.0.0
  - lxml>=4.9.3
  - numba>=0.58.0
  - pip:
    - PyQt6>=6.5.0
    - pydantic>=2.4.0
    - click>=8.1.7
    - loguru>=0.7.2
    - reportlab>=4.0.4
    - pytest>=7.4.2
    - pytest-cov>=4.1.0
    - pytest-qt>=4.2.0
    - pytest-mock>=3.11.1
    - black>=23.7.0
    - mypy>=1.5.1
    - flake8>=6.0.0
    - isort>=5.12.0
    - pylint>=2.17.5
    - sphinx>=7.1.2
    - sphinx-rtd-theme>=1.3.0
    - PyInstaller>=5.13.2
    - wheel>=0.41.2
    - build>=0.10.0
    - pre-commit>=3.4.0
    - memory-profiler>=0.61.0
